# Generated by Django 6.0.3 on 2026-04-19 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('biography', models.TextField()),
                ('nationality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('ready', 'Ready to Borrow'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('fulfilled', 'Fulfilled')], default='waiting', max_length=20)),
                ('notified_date', models.DateField(blank=True, null=True)),
                ('queue_position', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['reserved_date'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('publication_year', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.author')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_requested_date', models.DateField(blank=True, null=True)),
                ('return_verified_date', models.DateField(blank=True, null=True)),
                ('return_status', models.CharField(choices=[('none', 'No Request'), ('pending', 'Pending Return'), ('verified', 'Returned & Verified'), ('rejected', 'Return Rejected'), ('disputed', 'Disputed')], default='none', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book')),
            ],
        ),
    ]
