# Generated by Django 6.0.3 on 2026-05-13 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_semester_alter_loan_semester'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
    ]
