# Generated by Django 6.0.3 on 2026-05-13 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-loan_date']},
        ),
    ]
