# Generated by Django 6.0.3 on 2026-03-29 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_book_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
    ]
