# Generated by Django 6.0.3 on 2026-03-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='return_status',
            field=models.CharField(choices=[('pending', 'Pending Return'), ('verified', 'Returned & Verified'), ('rejected', 'Return Rejected'), ('disputed', 'Disputed')], default='pending', max_length=20),
        ),
    ]
