# Generated by Django 6.0.3 on 2026-03-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_loan_return_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='return_status',
            field=models.CharField(choices=[('none', 'No Request'), ('pending', 'Pending Return'), ('verified', 'Returned & Verified'), ('rejected', 'Return Rejected'), ('disputed', 'Disputed')], default='none', max_length=20),
        ),
    ]
