# Generated by Django 6.0.3 on 2026-03-30 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_loan_return_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('ready', 'Ready to Borrow'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('fulfilled', 'Fulfilled')], default='waiting', max_length=20)),
                ('notified_date', models.DateField(blank=True, null=True)),
                ('queue_position', models.PositiveIntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='app.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='app.member')),
            ],
            options={
                'ordering': ['reserved_date'],
                'unique_together': {('member', 'book', 'status')},
            },
        ),
    ]
